name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
    sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  http: ^1.6.0
  flutter_spinkit: ^5.2.2
  glassmorphism: ^3.0.0
  sensors_plus: ^5.0.1
  flutter_dotenv: ^6.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900
